### ISSUE TITLE
Error Creating SSL

### ISSUE THREAD

**Issue by ghost** [getcleaver/cleaver#2]
Error Code/Message:

> localhost | FAILED | rc=1 >> IMPORTANT NOTES: - The following errors were reported by the server: Domain: www.astralgeek33.com Type: unauthorized Detail: Invalid response from http://www.astralgeek33.com/.well-known/acme-challenge/jH1FnPdg0b8bSn5vFhET-Joo3y3GDgO3B1j71cs_EnI [165.227.187.255]: 404 Domain: astralgeek33.com Type: unauthorized Detail: Invalid response from http://astralgeek33.com/.well-known/acme-challenge/FoDKuXsretK8v7fQ73ofcLekH_2hSLJ1g1bWwR6ODzc [165.227.187.255]: 404 To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.Saving debug log to /var/log/letsencrypt/letsencrypt.log Plugins selected: Authenticator webroot, Installer None Obtaining a new certificate Performing the following challenges: http-01 challenge for astralgeek33.com http-01 challenge for www.astralgeek33.com Using the webroot path /home/cleaver/astralgeek33.com/current for all unmatched domains. Waiting for verification... Cleaning up challenges Failed authorization procedure. www.astralgeek33.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.astralgeek33.com/.well-known/acme-challenge/jH1FnPdg0b8bSn5vFhET-Joo3y3GDgO3B1j71cs_EnI [165.227.187.255]: 404, astralgeek33.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://astralgeek33.com/.well-known/acme-challenge/FoDKuXsretK8v7fQ73ofcLekH_2hSLJ1g1bWwR6ODzc [165.227.187.255]: 404non-zero return code

Note: The URL currently points to a WordPress installation on a different server in case you're wondering; I had to use a domain since Cleaver doesn't allow you to create an site without one.

**Comment by ashokgelal** [comment]
Let's Encrypt needs your domain to be pointed to the right server to verify that you own both the server and the domain. To avoid this error, don't install the SSL certificate when creating a site (i.e. uncheck `SECURE WITH LET'S ENCRYPT` option. You can always install the certificates later once your domain is pointing to the right server.
